//! Claimr — a constraint logic programming language (Prolog III inspired).
//!
//! This crate currently provides the front end: the [`ast`] (with exact
//! rational [`Number`]s — no floating point) and a parser
//! generated by [rustemo](https://crates.io/crates/rustemo) from the
//! authoritative grammar `src/parser/claimr.rustemo`. Evaluation and
//! constraint solving are future work.
//!
//! ```
//! use claimr::{parse_program, Clause};
//!
//! let clauses = parse_program("human(socrates).\n?- human(socrates).\n").unwrap();
//! assert!(matches!(clauses[0], Clause::Fact(_)));
//! assert!(matches!(clauses[1], Clause::Query(_)));
//! ```

pub mod ast;
pub mod number;
mod parser;

pub use ast::*;
pub use number::{Number, ParseNumberError};

use rustemo::Parser as _;

/// A syntax error, with its position in the source when known.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub struct ParseError {
    /// What went wrong, including the tokens the parser expected.
    pub message: String,
    /// 1-based line of the offending position, if known.
    pub line: Option<usize>,
    /// 1-based column of the offending position, if known.
    pub column: Option<usize>,
    /// Byte offset of the offending position, if known.
    pub offset: Option<usize>,
}

impl std::fmt::Display for ParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match (self.line, self.column) {
            (Some(line), Some(column)) => write!(f, "{line}:{column}: {}", self.message),
            (Some(line), None) => write!(f, "{line}: {}", self.message),
            _ => f.write_str(&self.message),
        }
    }
}

impl From<rustemo::Error> for ParseError {
    fn from(err: rustemo::Error) -> Self {
        match err {
            rustemo::Error::ParseError(e) => {
                let start = e.span.map(|s| s.start);
                ParseError {
                    message: e.message,
                    line: start.and_then(|p| p.line()),
                    column: start.and_then(|p| p.column()).map(|c| c + 1),
                    offset: start.map(|p| p.pos),
                }
            }
            rustemo::Error::IOError(e) => ParseError {
                message: e.to_string(),
                line: None,
                column: None,
                offset: None,
            },
        }
    }
}

/// Parse a whole program — a sequence of clauses — from source text.
///
/// The entire input must be consumed; whitespace between clauses is ignored.
pub fn parse_program(source: &str) -> Result<Vec<Clause>, ParseError> {
    parser::claimr::ClaimrParser::new()
        .parse(source)
        .map_err(ParseError::from)
}

/// Parse exactly one clause from source text.
///
/// Fails if the input holds zero clauses or more than one.
pub fn parse_clause(source: &str) -> Result<Clause, ParseError> {
    let mut clauses = parse_program(source)?;
    match clauses.len() {
        1 => Ok(clauses.remove(0)),
        n => Err(ParseError {
            message: format!("expected exactly one clause, found {n}"),
            line: None,
            column: None,
            offset: None,
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_fact() {
        assert!(matches!(parse_clause("human(socrates)."), Ok(Clause::Fact(_))));
    }

    #[test]
    fn parses_rule() {
        assert!(matches!(parse_clause("mortal(X) :- human(X)."), Ok(Clause::Rule { .. })));
    }

    #[test]
    fn parses_constraint_fact() {
        assert!(matches!(
            parse_clause("{ age(socrates) > 70 }."),
            Ok(Clause::ConstraintFact(_))
        ));
    }

    #[test]
    fn parses_constraint_rule() {
        assert!(matches!(
            parse_clause("eligible(X) :- { age(X) >= 18 }."),
            Ok(Clause::ConstraintRule { .. })
        ));
    }

    #[test]
    fn parses_implication() {
        assert!(matches!(
            parse_clause("{ age(X) >= 18 } => eligible(X)."),
            Ok(Clause::Implication { .. })
        ));
    }

    #[test]
    fn parses_query() {
        assert!(matches!(
            parse_clause("?- eligible(alice), { age(alice) >= 18 }."),
            Ok(Clause::Query(_))
        ));
    }

    #[test]
    fn parses_query_with_only_a_constraint_block() {
        let Clause::Query(body) = parse_clause("?- { X > 1, X < 10 }.").unwrap() else {
            panic!("expected query");
        };
        assert_eq!(body.len(), 1);
        assert!(matches!(body[0], Goal::Constraint(ref c) if c.terms.len() == 2));
    }

    #[test]
    fn parses_program() {
        let input = "human(socrates).\nmortal(X) :- human(X).\n\n?- mortal(socrates).\n";
        let clauses = parse_program(input).expect("program parses");
        assert_eq!(clauses.len(), 3);
    }

    #[test]
    fn empty_program_is_ok() {
        assert_eq!(parse_program("").unwrap(), vec![]);
        assert_eq!(parse_program("  \n\n").unwrap(), vec![]);
    }

    #[test]
    fn nested_atoms_as_arguments() {
        let clause = parse_clause("likes(mary, father(john)).").unwrap();
        let Clause::Fact(atom) = clause else { panic!("expected fact") };
        assert_eq!(atom.name, "likes");
        assert_eq!(atom.args[0], Expr::Ident("mary".into()));
        assert_eq!(
            atom.args[1],
            Expr::Atom(Box::new(Atom { name: "father".into(), args: vec![Expr::Ident("john".into())] }))
        );
    }

    #[test]
    fn numbers_and_variables() {
        let Clause::ConstraintFact(c) = parse_clause("{ X >= 18.5, Y != 3 }.").unwrap() else {
            panic!("expected constraint fact");
        };
        assert_eq!(c.terms[0].left, Expr::Var("X".into()));
        assert_eq!(c.terms[0].op, RelOp::Ge);
        assert_eq!(c.terms[0].right, Expr::Number(Number::from_ratio(37, 2).unwrap()));
        assert_eq!(c.terms[1].op, RelOp::Neq);
        assert_eq!(c.terms[1].right, Expr::Number(Number::from(3)));
    }

    #[test]
    fn all_relops() {
        for (src, op) in [
            ("=", RelOp::Eq), ("!=", RelOp::Neq), ("<", RelOp::Lt),
            (">", RelOp::Gt), ("<=", RelOp::Le), (">=", RelOp::Ge),
        ] {
            let Clause::ConstraintFact(c) = parse_clause(&format!("{{ X {src} 1 }}.")).unwrap() else {
                panic!("expected constraint fact for {src}");
            };
            assert_eq!(c.terms[0].op, op, "operator {src}");
        }
    }

    #[test]
    fn error_carries_position() {
        // Missing closing paren: the `.` on line 2 sits at column 21 (1-based).
        let err = parse_program("human(socrates).\nmortal(X) :- human(X.\n").unwrap_err();
        assert_eq!(err.line, Some(2));
        assert_eq!(err.column, Some(21));
        assert!(err.message.contains("Expected"), "message: {}", err.message);
        assert!(err.to_string().starts_with("2:21: "), "display: {err}");
    }

    #[test]
    fn missing_terminating_dot_is_an_error() {
        let err = parse_program("human(socrates)").unwrap_err();
        assert_eq!(err.line, Some(1));
    }

    #[test]
    fn parse_clause_rejects_multiple_clauses() {
        let err = parse_clause("a(x). b(y).").unwrap_err();
        assert!(err.message.contains("exactly one clause"));
    }
}
